dist: trusty
language: python
python:
  - '3.6'
before_install:
# Install conda
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $HOME/miniconda"
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
# - conda install --yes scipy pytest pytest-cov pandas pytables astropy
- pip install scipy pytest pytest-cov pandas tables astropy
- pip install spiceypy --no-cache-di
# Install CDF library
- wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf36_3_1/linux/cdf36_3_1-dist-all.tar.gz
- tar -zxvf cdf36_3_1-dist-all.tar.gz
- cd cdf36_3-dist
- make OS=linux ENV=gnu all
- sudo make INSTALLDIR=/usr/local/cdf install
- cd ../
# Install SPICE library
- sudo apt install csh
- mkdir spice
- cd spice
- wget http://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z
- wget http://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/importCSpice.csh
- csh -f importCSpice.csh
- cd ../
script:
# Check that unit tests work
- pytest heliopy/ --cov=heliopy/ -v --durations=5
# Check building a source distribution works
- python setup.py sdist
after_success:
- pip install codecov
- codecov
