dist: trusty
language: python
python:
- '3.6'
cache:
  directories:
    - $HOME/miniconda
before_install:
- chmod ugo+x ./ci/install_conda.sh
- bash ./ci/install_conda.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate testenv
- conda install --yes scipy pytest pytest-cov pandas pytables

- wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf36_3_1/linux/cdf36_3_1-dist-all.tar.gz
- tar -zxvf cdf36_3_1-dist-all.tar.gz
- cd cdf36_3-dist
- make OS=linux ENV=gnu all
- sudo make INSTALLDIR=/usr/local/cdf install
- cd ../
script:
- pytest heliopy/ --cov=heliopy/ -v --durations=5
after_success:
- pip install codecov
- codecov
